apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: rabbitmq-logs
  name: rabbitmq-logs
  namespace: nf-etl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
